name: Update

on:
  push:
    branches: ["*"]
  schedule:
    - cron: "* */12 * * *"

jobs:
  update-readme:
    name: Update Code Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.GH_TOKEN  }}
          GH_TOKEN: ${{ secrets.WAKA_TIME_API_KEY }}
          SHOW_PROFILE_VIEWS: "True"
          SHOW_OS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
